version: "3.7"

volumes:
  sdvolume:
    name: sd-volume

networks:
  sdnetwork:
    name: sd-network

services:
  pg:
    image: postgres:13.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - sdvolume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - sdnetwork
  sd-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
    env_file:
      - .env
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - sdnetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
